---
title: "Gráficos de Pontes (Waterfall)"
author: "Curso-R"
date: "31/07/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pacotes

```{r}
library(tidyverse)
library(waterfall)
library(plotly)
```


## ggplot2

```{r}
# colunas auxiliares
balanco <- balanco %>%
  mutate(
    fim = lead(cumsum(valor), default = 0),
    inicio = lag(fim, default = 0)
  )

balanco
```

```{r}
ggplot(balanco) +
  geom_rect(aes(x = ocorrencia, fill = tipo, xmin = seq - 0.4, xmax = seq + 0.4, ymin = fim, ymax = inicio))
```






## plotly

```{r, warning=FALSE, message=FALSE}
library(plotly)

x= list("Sales", "Consulting", "Net revenue", "Purchases", "Other expenses", "Profit before tax")
measure= c("relative", "relative", "total", "relative", "relative", "total")
text= c("+60", "+80", "", "-40", "-20", "Total")
y= c(60, 80, 0, -40, -20, 0)
data = data.frame(x=factor(x,levels=x),measure,text,y)
data
```

```{r}
p <- plot_ly(
  data, name = "20", type = "waterfall", measure = ~measure,
  x = ~x, textposition = "outside", y= ~y, text =~text,
  connector = list(line = list(color= "rgb(63, 63, 63)"))) %>%
  layout(title = "Profit and loss statement 2018",
        xaxis = list(title = ""),
        yaxis = list(title = ""),
        autosize = TRUE,
        showlegend = TRUE)
p
```

